config/routes.rb
Rails.application.routes.draw do
  
  root 'top_pages#top'

  resources :users, only: %i[new create]
  
  get 'sign_up', to: 'users#new'
  get 'select_sign_up', to: 'users#select'
  get 'app_top', to: 'top_pages#app_top'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'guide_spotify_login', to: 'user_sessions#guide_spotify_login'

  post 'oauth/callback', to: 'google#callback'
  get 'oauth/callback', to: 'google#callback'
  get 'oauth/:provider', to: 'google#oauth', as: 'auth_at_provider'

  get 'user_sessions/google_auth', to: 'user_sessions#google_auth', as: 'google_login'
  get 'users/google_auth', to: 'users#google_auth', as: 'google_signup'
  
  get '/spotify_login', to: 'spotify#login'
  get '/spotify_callback', to: 'spotify#callback'

  get 'pre_sign_up', to: 'pre_sign_ups#new'
  post 'pre_sign_up', to: 'pre_sign_ups#create'
  get 'pre_sign_up_completed', to: 'pre_sign_ups#completed'

  resources :favorite_artists, only: %i[index create destroy] do
    collection do
      get :search
    end
  end

  get 'favorite_artists/new'

  resources :favorite_tracks, only: %i[index create destroy] do
    collection do
      get :search
    end
  end

  get 'favorite_tracks/new'

  get 'playlists/select'
  resources :playlists, only: %i[show index destroy edit update]

  resources :create_playlist_artists, only: %i[index create]

  resources :create_playlist_genres, only: %i[index create]

  resources :password_resets, only: %i[create edit update new]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :favorite_artists
  has_many :tracks

  validates :name, presence: true
  validates :spotify_id, presence: true
end

app/models/favorite_track.rb
class FavoriteTrack < ApplicationRecord
  belongs_to :user
  belongs_to :track
end

app/controllers/favorite_tracks_controller.rb
class FavoriteTracksController < ApplicationController
  before_action :ensure_spotify_token_valid, only: %i[create]
  before_action :set_favorite_track, only: %i[destroy]

  def index
    @favorite_tracks = FavoriteTrack.where(user: current_user).page(params[:page]).per(20)
    @track_ids = @favorite_tracks.map { |fa| fa.track.spotify_id }
  end

  def create
    track_params = favorite_track_params
    track_id = track_params[:track_id]
    track_name = track_params[:track_name]
    artist_name = track_params[:artist_name]

    # 楽曲が選択されていなかった場合、処理を終了
    if track_id.blank?
      return
    end

    if Track.exists?(spotify_id: track_id)
      @track = Track.find_by(spotify_id: track_id)
    else
      # トラックのアーティストIDを取得
      track = RSpotify::Track.find(track_id)
      artist_id = track.artists.first.id
      if Artist.exists?(spotify_id: artist_id)
        @artist = Artist.find_by(spotify_id: artist_id)
      else
        @artist = Artist.new(name: artist_name, spotify_id: artist_id)
      end
      # 分析情報を取得
      headers = {
        Authorization: "Bearer #{session[:spotify_access_token]}"
      }
      response = RestClient.get("https://api.spotify.com/v1/audio-features/#{track_id}", headers)
      data = JSON.parse(response.body)

      energy = data['energy']
      key = data['key']
      tempo = data['tempo']

      @track = Track.new(name: track_name, spotify_id: track_id, artist: @artist, energy: energy, key: key, tempo: tempo)
      unless @track.save
        flash[:error] = "楽曲の登録に失敗しました"
        render 'new'
        return
      end
    end

    if FavoriteTrack.exists?(user: current_user, track: @track)
      flash[:alert] = "すでにお気に入りに登録済みです"
      redirect_to favorite_tracks_path
    else
      @favorite_track = FavoriteTrack.new(user: current_user, track: @track)
      if @favorite_track.save
        flash[:success] = 'お気に入りに追加しました'
        redirect_to favorite_tracks_path
      else
        flash[:error] = 'お気に入りの登録に失敗しました'
        render 'new'
      end
    end
  end

  def new; end

  def search
    track_name = params[:track_name]
    artist_name = params[:artist_name]
    
    if artist_name.present? && track_name.present?
      query = "track:\"#{track_name}*\" artist:\"#{artist_name}\""
    elsif track_name.present?
      query = "track:\"#{track_name}*\""
    elsif artist_name.present?
      query = "artist:\"#{artist_name}\""
    end

    if query.present?
      @tracks = RSpotify::Track.search(query, market:'JP', limit:50)
      if @tracks.blank?
        flash.now[:alert] = '該当する楽曲が見つかりませんでした'
      end
    else
      flash.now[:warning] = '楽曲名またはアーティスト名を入力してください'
    end
    render 'new'
  end

  def destroy
    @favorite_track.destroy!
    flash[:success] = 'お気に入りから削除しました'
    redirect_to favorite_tracks_path, status: :see_other
  end

  private

  def favorite_track_params
    params.require(:favorite_track).permit(:track_id, :track_name, :artist_name)
  end

  def set_favorite_track
    @favorite_track = FavoriteTrack.find(params[:id])
  end
end

app/helpers/favorite_tracks_helper.rb
module FavoriteTracksHelper
end

app/views/favorite_tracks/_delete_button.html.erb
<button class="btn btn-square btn-sm", onclick="document.getElementById('delete_confirmation_<%= track_id %>').showModal()">
  <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" /></svg>
</button>

<!-- ダイアログを表示 -->
<dialog id="delete_confirmation_<%= track_id %>" class="modal">
  <div class="modal-box">
    <p class="text-center">
      <%= "#{Track.find_by(spotify_id: track_id).name}をお気に入りから削除しますか?" %>
    </p>
    <div class="modal-action">
      <form method="dialog">
        <button class="btn">キャンセル</button>
      </form>
      <% favorite_track = FavoriteTrack.find_by(track: Track.find_by(spotify_id: track_id), user: current_user) %>
      <%= button_to "削除する", favorite_track_path(favorite_track), method: :delete, class: "btn btn-warning" %>
    </div>
  </div>
</dialog>

app/views/favorite_tracks/_search_form.html.erb
<!-- 楽曲検索フォーム -->
<div class="flex justify-center py-6">
  <div class="join w-full">
    <%= form_with url: search_favorite_tracks_path, method: :get, class: "w-full flex justify-center" do |f| %>
      <%= f.text_field :track_name, class: "input input-bordered input-secondary w-1/4 join-item", placeholder: "楽曲名" %>
      <%= f.text_field :artist_name, class: "input input-bordered input-secondary w-1/4 join-item", placeholder: "アーティスト名" %>
      <%= f.submit "検索", class: "btn join-item bg-accent text-indigo-950 hover:bg-secondary rounded-r-full" %>
    <% end %>
  </div>
</div>

app/views/favorite_tracks/_track_card.html.erb
<div class="card w-64 bg-secondary shadow-xl">
  <div class="card-actions justify-end px-2 pt-2">  
    <%= render 'delete_button', track_id: track_id %>
  </div>  
  <figure class="pt-3">
    <!-- アルバム画像を取得 -->
    <% tracks = RSpotify::Track.find(track_id) %>
    <% if tracks.album.images.present? %>
      <% image = tracks.album.images.first %>
      <img src="<%= image['url'] %>?size=300x300" alt="Tracks Artwork" class="rounded-xl" style="width: 200px; height: 200px;" />
    <% else %>
      <img src="<%= image_path('20200501_noimage.png') %>" alt="Tracks Artwork" class="rounded-xl" style="width: 200px; height: 200px;" />
    <% end %>
  </figure>
  <div class="card-body items-center text-center">
    <h2 class="card-title text-indigo-950">  
      <%= Track.find_by(spotify_id: track_id).name %>
    </h2>
    <p class="text-indigo-950"><%= Artist.find_by(id: Track.find_by(spotify_id: track_id).artist).name %></p>
  </div>
</div>

app/views/favorite_tracks/_track_table.html.erb
<!-- 検索結果を表示するテーブル -->
<div class="flex justify-center">
    <div class="overflow-y-scroll border border-gray-200 p-4 w-4/5 h-[40vh] pt-0">
      <table class="table table-pin-rows">
        <thead>
          <tr>
            <th></th>
            <th>楽曲名</th>
            <th>アーティスト名</th>
            <th>収録</th>
          </tr>
        </thead>
        <tbody>
          <% if @tracks.present? %>
            <% @tracks.each do |track| %>
              <tr class="table-row cursor-pointer hover:bg-base-300">
                <td class="radio border-none">
                <%= f.radio_button :track_id, track.id, name: 'favorite_track[track_id]', class: "radio radio-accent", data: { track_name: track.name, artist_name: track.artists.map(&:name).join(', ') } %>
                </td>
                <td class="track-name"><%= "#{track.name} " %></td>
                <td class="track-artist"><%= "#{track.artists.map(&:name).join(', ')}" %></td>
                <td class="track-album"><%= "#{track.album.name}" %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/favorite_tracks/index.html.erb
<div class="flex justify-between w-full py-20 px-20">
    <h1 class="text-4xl font-bold font-body font-kosugi"><%= '楽曲一覧' %></h1>
    <%= link_to "お気に入り登録", favorite_tracks_new_path, class: "btn btn-lg btn-outline btn-accent rounded-full" %>
</div>

<!-- 楽曲表示 -->
<div class="flex justify-center">
  <div class="grid grid-cols-4 gap-10">
    <% @track_ids.each do |track_id| %>
      <%= render 'track_card', track_id: track_id %>
    <% end %>
  </div>
</div>

<div class="flex justify-center py-20">
  <%= paginate @favorite_tracks %>
</div>

app/views/favorite_tracks/new.html.erb
<div class="flex justify-between px-20 py-10">
  <h1 class="text-3xl font-bold font-body font-kosugi"><%= "お気に入り楽曲登録" %></h1>
  <div class="pr-10">
    <%= link_to "← 一覧に戻る", favorite_tracks_path, class: "btn btn-outline btn-accent rounded-full" %>
  </div>
</div>

<%= render 'search_form' %>

<%= form_with url: favorite_tracks_path, method: :post do |f| %>
  <%= render 'track_table', f: f %>
  <%= f.hidden_field :track_name, value: "", name: "favorite_track[track_name]" %>
  <%= f.hidden_field :artist_name, value: "", name: "favorite_track[artist_name]" %>
  <div class="flex justify-end pt-10 px-40">
    <%= f.submit "登録",  class: "btn btn-lg btn-active btn-accent text-indigo-950 hover:bg-base-100 hover:text-accent rounded-full px-10" %>
  </div>
<% end %>