config/routes.rb
Rails.application.routes.draw do
  
  root 'top_pages#top'

  resources :users, only: %i[new create]
  
  get 'sign_up', to: 'users#new'
  get 'select_sign_up', to: 'users#select'
  get 'app_top', to: 'top_pages#app_top'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'guide_spotify_login', to: 'user_sessions#guide_spotify_login'

  post 'oauth/callback', to: 'google#callback'
  get 'oauth/callback', to: 'google#callback'
  get 'oauth/:provider', to: 'google#oauth', as: 'auth_at_provider'

  get 'user_sessions/google_auth', to: 'user_sessions#google_auth', as: 'google_login'
  get 'users/google_auth', to: 'users#google_auth', as: 'google_signup'
  
  get '/spotify_login', to: 'spotify#login'
  get '/spotify_callback', to: 'spotify#callback'

  get 'pre_sign_up', to: 'pre_sign_ups#new'
  post 'pre_sign_up', to: 'pre_sign_ups#create'
  get 'pre_sign_up_completed', to: 'pre_sign_ups#completed'

  resources :favorite_artists, only: %i[index create destroy] do
    collection do
      get :search
    end
  end

  get 'favorite_artists/new'

  resources :favorite_tracks, only: %i[index create destroy] do
    collection do
      get :search
    end
  end

  get 'favorite_tracks/new'

  get 'playlists/select'
  resources :playlists, only: %i[show index destroy edit update]

  resources :create_playlist_artists, only: %i[index create]

  resources :create_playlist_genres, only: %i[index create]

  resources :password_resets, only: %i[create edit update new]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :favorite_artists
  has_many :tracks

  validates :name, presence: true
  validates :spotify_id, presence: true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/favorite_artist.rb
class FavoriteArtist < ApplicationRecord
  belongs_to :user
  belongs_to :artist
end

app/models/favorite_track.rb
class FavoriteTrack < ApplicationRecord
  belongs_to :user
  belongs_to :track
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  self.primary_key = 'id'

  belongs_to :user
end

app/models/pre_sign_up.rb
class PreSignUp < ApplicationRecord
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/track.rb
class Track < ApplicationRecord
  has_many :favorite_tracks
  belongs_to :artist

  validates :name, presence: true
  validates :spotify_id, presence: true
  validates :artist, presence: true
  validates :energy, presence: true
  validates :key, presence: true
  validates :tempo, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :favorite_artists, dependent: :destroy
  has_many :favorite_tracks, dependent: :destroy
  has_many :playlists, dependent: :destroy
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true, presence: true
  validates :name, presence: true, length: { maximum: 255 }

  validates :reset_password_token, uniqueness: true, allow_nil: true
end

app/controllers/google_controller.rb
class GoogleController < ApplicationController
  skip_before_action :require_login

  def oauth
    session[:state] = auth_params[:state]
    login_at(auth_params[:provider])
  end

  def callback
    provider = auth_params[:provider]
    state = session[:state]
    session.delete(:state)

    sorcery_fetch_user_hash(provider)
    session[:uid] = @user_hash[:uid]
    session[:provider] = provider

    if state == 'signup'
      user_info = @user_hash[:user_info]
      session[:email] = user_info['email']
      session[:name] = user_info['name']
      redirect_to google_signup_path
    elsif state == 'login'
      redirect_to google_login_path
    else
      redirect_to root_path, alert: "Invalid authentication type."
    end
  end

  private

  def auth_params
    params.permit(:code, :provider, :state)
  end
end

app/controllers/spotify_controller.rb
require 'rest-client'
require 'json'

class SpotifyController < ApplicationController
  def login
    client_id = ENV['SPOTIFY_CLIENT_ID']
    redirect_url = callback_url
    scope = 'playlist-modify-private  user-read-private playlist-modify-public'
    spotify_url ="https://accounts.spotify.com/authorize?client_id=#{client_id}&response_type=code&redirect_uri=#{redirect_url}&scope=#{scope}"

    # 外部ホストへのリダイレクを許可するオプションを使用
    redirect_to spotify_url, allow_other_host: true
  end

  def callback
    code = params[:code]
    client_id = ENV['SPOTIFY_CLIENT_ID']
    client_secret = ENV['SPOTIFY_CLIENT_SECRET']
    redirect_url = callback_url

    response = RestClient.post('https://accounts.spotify.com/api/token', {
      grant_type: 'authorization_code',
      code: code,
      redirect_uri: redirect_url,
      client_id: client_id,
      client_secret: client_secret
    },{
      Accept: 'application/json'
    })

    response_data = JSON.parse(response.body)
    access_token = response_data['access_token']
    refresh_token = response_data['refresh_token']

    # アクセストークンとリフレッシュトークンをセッションに保存
    session[:spotify_access_token] = access_token
    session[:spotify_refresh_token] = refresh_token

    flash[:success] = 'ログインしました'
    redirect_to app_top_path
  end

  private

  def callback_url
    "http://localhost:3001/spotify_callback"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create google_auth select]

  def new
    @user = User.new
  end

  def select; end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザー登録が完了しました'
      redirect_to login_path
    else
      flash[:error] = 'ユーザー登録に失敗しました'
      redirect_to sign_up_path
    end
  end

  def google_auth
    uid = session[:uid]
    provider = session[:provider]
    name = session[:name]
    email = session[:email]

    session.delete(:uid)
    session.delete(:provider)
    session.delete(:name)
    session.delete(:email)

    auth = Authentication.find_by(uid: uid, provider: provider)
    user = User.find_by(id: auth.user_id) if auth
    if user
      flash[:error] = 'すでにこのGoogleアカウントは登録されています'
      redirect_to login_path
    else
      password = SecureRandom.hex(16)
      @user = User.new(
        name: name,
        email: email,
        password: password,
        password_confirmation: password
      )

      if @user.save
        @authenticate = Authentication.new(
          user_id: @user.id,
          uid: uid,
          provider: provider,
        )

        if @authenticate.save
          flash[:success] = 'Googleアカウントでのユーザー登録が完了しました'
          redirect_to login_path
        else
          flash[:error] = 'ユーザー登録に失敗しました'
          redirect_to select_sign_up_path
        end
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/pre_sign_ups_helper.rb
module PreSignUpsHelper
end

app/helpers/spotify_helper.rb
module SpotifyHelper
end

app/helpers/top_pages_helper.rb
module TopPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_after_login_header.html.erb
<header>
  <div class="navbar bg-base-300">
    <div class="flex justify-between w-full h-1/6">
      <div class="w-1/6 py-10 px-5">
        <label class="text-xl font-logo"><%= "Discover music" %></label>
      </div>
      <div class="flex justify-between items-center w-1/4">
        <h1><%= "#{current_user.name}" %><h1>
        <div class=" px-4">
        <%= link_to "ログアウト", logout_path, role: "button", class: "btn btn-outline btn-primary text-xs", data: { turbo_method: :delete } %>
        </div>
      </div> 
    </div>
  </div> 
</header>

app/views/shared/_before_login_header.html.erb
<header>
  <div class="navbar bg-base-300">
    <div class="flex justify-between w-full h-1/6 ">
      <div class="w-1/6 py-5 px-3">
        <%= link_to 'Discover music', root_path, role:"button", class:"btn btn-ghost text-xl" %>
      </div>
      <div class="flex flex-row justify-end w-1/6 px-4 gap-5">
        <%= link_to "新規登録", pre_sign_up_path, class: "btn btn-outline btn-primary" %>
        <%= link_to "ログイン", login_path, class: "btn btn-outline btn-primary" %>
      </div>
    </div>
  </div> 
</header>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> flex items-center">
    <% if message_type == 'error' %>
      <div class="alert alert-error">
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
        <span><%= message %></span>
      </div>
    <% elsif message_type == 'success' %>
      <div class="alert alert-success">
        <svg http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
        <span><%= message %></span>
      </div>
    <% elsif message_type == 'warning' %>
      <div class="alert alert-warning">
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
        <span><%= message %></span>
      </div>
    <% elsif message_type =='alert' %>
      <div class="alert" >
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="stroke-info shrink-0 w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
        <span><%= message %></span>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <div class="navbar bg-base-300 pb-0 pr-0">
    <div class="flex justify-between w-full h-1/6">  
      <div class="w-1/6 px-3">
        <%= link_to image_tag('logo2.png', class: "h-full"), app_top_path, class:"btn h-full py-0" %>
      </div>
      <div class="flex flex-col w-1/4">
        <div class="flex justify-between items-center w-full">
          <h1><%= "#{current_user.name}" %></h1>
          <div class=" px-4">
            <%= link_to 'ログアウト', logout_path, method: :delete, class: "btn btn-outline btn-primary text-xs", data: { turbo_method: :delete }  %>
          </div>
        </div> 
        <div class="flex flex-row">
          <div class="justify-end w-full">
            <div class="dropdown dropdown-hover pt-4 w-full">
              <div tabindex="0" role="button" class="btn btn-ghost bg-change w-full">プレイリスト</div>
                <ul tabindex="0" class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-full">
                  <li><%= link_to '新規作成', playlists_select_path %></li>
                  <li><%= link_to '一覧', playlists_path %></li>
                </ul>
              </div>
            </div>
            <div class="dropdown dropdown-hover pt-4 w-full">
              <div tabindex="0" role="button" class="btn btn-ghost bg-change w-full">お気に入り</div>
                <ul tabindex="0" class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-full">
                  <li><%= link_to 'アーティスト', favorite_artists_path %></li>
                  <li><%= link_to '楽曲', favorite_tracks_path %></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/shared/_sign_up_header.html.erb
<header>
  <div class="navbar bg-base-300 py-0">
    <div class="flex justify-between w-full h-1/6 ">
      <div class="w-1/6 px-3 ">
        <%= image_tag('logo2.png', class: "h-full py-0") %>
      </div>
    </div>
  </div> 
</header>