config/routes.rb
Rails.application.routes.draw do
  
  root 'top_pages#top'

  resources :users, only: %i[new create]
  
  get 'sign_up', to: 'users#new'
  get 'select_sign_up', to: 'users#select'
  get 'app_top', to: 'top_pages#app_top'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'guide_spotify_login', to: 'user_sessions#guide_spotify_login'

  post 'oauth/callback', to: 'google#callback'
  get 'oauth/callback', to: 'google#callback'
  get 'oauth/:provider', to: 'google#oauth', as: 'auth_at_provider'

  get 'user_sessions/google_auth', to: 'user_sessions#google_auth', as: 'google_login'
  get 'users/google_auth', to: 'users#google_auth', as: 'google_signup'
  
  get '/spotify_login', to: 'spotify#login'
  get '/spotify_callback', to: 'spotify#callback'

  get 'pre_sign_up', to: 'pre_sign_ups#new'
  post 'pre_sign_up', to: 'pre_sign_ups#create'
  get 'pre_sign_up_completed', to: 'pre_sign_ups#completed'

  resources :favorite_artists, only: %i[index create destroy] do
    collection do
      get :search
    end
  end

  get 'favorite_artists/new'

  resources :favorite_tracks, only: %i[index create destroy] do
    collection do
      get :search
    end
  end

  get 'favorite_tracks/new'

  get 'playlists/select'
  resources :playlists, only: %i[show index destroy edit update]

  resources :create_playlist_artists, only: %i[index create]

  resources :create_playlist_genres, only: %i[index create]

  resources :password_resets, only: %i[create edit update new]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  self.primary_key = 'id'

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :favorite_artists, dependent: :destroy
  has_many :favorite_tracks, dependent: :destroy
  has_many :playlists, dependent: :destroy
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true, presence: true
  validates :name, presence: true, length: { maximum: 255 }

  validates :reset_password_token, uniqueness: true, allow_nil: true
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :ensure_spotify_token_valid, only: %i[show edit update destroy]
  before_action :set_playlist, only: %i[show edit update destroy]

  def select; end

  def index
    @user_playlist = Playlist.where(user: current_user).page(params[:page]).per(10)
    @playlist_ids = @user_playlist.map { |fa| fa.spotify_id }
  end

  def show
    playlist_status
    set_playlist_items
  end

  def edit
    @playlist_name = @playlist.name
    playlist_status
    set_playlist_items
  end

  def update
    playlist_params = set_playlist_params
    playlist_name = playlist_params[:playlist_name]
    public_status = playlist_params[:public_status] == 'public'
    new_playlist_items = JSON.parse(playlist_params[:playlist_items])
    current_playlist_items = JSON.parse(playlist_params[:current_playlist_items])

    @playlist.update(name: playlist_name)

    playlist_id = @playlist.spotify_id

    playlist_update = RestClient.put(
      "https://api.spotify.com/v1/playlists/#{playlist_id}",
      {
        name: playlist_name,
        public: public_status
      }.to_json,
      {
        Authorization: "Bearer #{session[:spotify_access_token]}",
        content_type: :json,
        accept: :json
      }
    )

    if new_playlist_items != current_playlist_items
      headers = {
        Authorization: "Bearer #{session[:spotify_access_token]}",
        content_type: :json
      }

      RestClient.put(
        "https://api.spotify.com/v1/playlists/#{playlist_id}/tracks",
        { uris: [] }.to_json,
        headers
      )

      uris = new_playlist_items.map { |item| "spotify:track:#{item[2]}"}
      RestClient.post(
        "https://api.spotify.com/v1/playlists/#{playlist_id}/tracks",
        { uris: uris }.to_json,
        headers
      )
    end

    flash[:success] = "プレイリストを変更しました"
    redirect_to playlist_path(@playlist)

  end

  def destroy
    playlist_id = @playlist.spotify_id

    headers = {
      Authorization: "Bearer #{session[:spotify_access_token]}"
    }

    RestClient.delete("https://api.spotify.com/v1/playlists/#{playlist_id}/followers", headers)
    
    @playlist.destroy!
    flash[:success] = "プレイリストを削除しました"
    redirect_to playlists_path, status: :see_other
  end

  private
  
  def set_playlist
    @playlist = Playlist.find(params[:id])
  end

  def set_playlist_params
    params.require(:playlist).permit(:playlist_name, :public_status, :playlist_items, :current_playlist_items)
  end

  def playlist_status
    playlist_id = Playlist.find_by(id: @playlist).spotify_id

    # プレイリストがプロフィールで公開されているかを確認
    user_playlists = RestClient.get(
      "https://api.spotify.com/v1/me/playlists",
      {
        Authorization: "Bearer #{session[:spotify_access_token]}",
        content_type: :json
      }
    )

    playlists_info = JSON.parse(user_playlists.body)
    playlist_ids = playlists_info['items'].map { |playlist| playlist['id'] }

    @playlist_public = playlist_ids.include?(playlist_id)
  end

  def set_playlist_items
    playlist_id = Playlist.find_by(id: @playlist).spotify_id

    #プレイリスト収録曲の確認
    playlist_items = RestClient.get(
      "https://api.spotify.com/v1/playlists/#{playlist_id}/tracks",
      {
        Authorization: "Bearer #{session[:spotify_access_token]}",
        content_type: :json
      }
    )

    playlist_tracks = JSON.parse(playlist_items.body)

    playlist_item = []

    playlist_tracks['items'].each do |track|
      track_info = track['track']
      track_name = track_info['name']
      artist_name = track_info['artists'].map { |artist| artist['name'] }.join(', ')
      track_id = track_info['id']
      playlist_item << [track_name, artist_name, track_id]
    end

    @playlist_items = playlist_item
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_delete_playlist.html.erb
<button class="btn btn-outline btn-primary rounded-full" onclick="document.getElementById('delete_confirmation_<%= playlist_id %>').showModal()">
  <span><%= "削除" %></span>
</button>

<!-- ダイアログ表示 -->
<dialog id="delete_confirmation_<%= playlist_id %>" class="modal">
  <div class="modal-box">
    <p class="text-center">
      <%= "#{Playlist.find_by(spotify_id: playlist_id).name}を削除しますか?" %>
    </p>
    <div class="modal-action">
      <form method="dialog">
        <button class="btn">キャンセル</button>
      </form>
      <% playlist = Playlist.find_by(spotify_id: playlist_id) %>
      <%= button_to "削除する", playlist_path(playlist), method: :delete, class: "btn btn-warning" %>
    </div>
  </div>
</dialog>

app/views/playlists/_playlist_card.html.erb
<div class="border border-4 border-sky-400 w-3/4 rounded-2xl"> 
  <div class="card card-side w-full flex justify-center bg-neutral">
    <figure class="px-5 py-5">
      <% playlist = RSpotify::Playlist.find(nil, playlist_id) %>
      <% if playlist.images.any? %>
        <% image = playlist.images.first %>
        <img src="<%= image['url'] %>?size=300x300" alt="Playlist Artwork" class="rounded-xl" style="width: 250px; height: 250px;" />
      <% else %>
        <img src="<%= image_path('20200501_noimage.png') %>" alt="Playlist Artwork" class="rounded-xl" style="width: 200px; height: 200px;" />
      <% end %>
    </figure>
    <div class="card-body items-center text-center">
      <% playlist_name = Playlist.find_by(spotify_id: playlist_id).name %>
      <% playlist = Playlist.find_by(spotify_id: playlist_id) %>
      <h2 class="card-title pt-10 pb-3 pr-5 link"><%= link_to "#{playlist_name}", playlist_path(playlist),  method: :get %></h2>
      <% create_date = Playlist.find_by(spotify_id: playlist_id).date %>
      <p class="flex flex-row-reverse px-2"><%= "作成日 : #{create_date}" %></p>
      <%= render "delete_playlist", playlist_id: playlist_id %>
    </div>
  </div>
</div>

app/views/playlists/edit.html.erb
<%= form_with model: @playlist, url: playlist_path(@playlist), method: :put do |f| %>
  <div class="grid grid-cols-2 w-full">
    <div class="flex flex-col pt-20 pl-10 w-full">
      <%= f.label :プレイリスト名, class: 'py-5' %>
      <%= f.text_field :playlist_name, class: 'form-control input input-bordered input-secondary w-full', value: @playlist_name %>
    </div>
    <div class="flex flex-col w-full justify-center pt-20">
      <%= f.label :公開状況, class: 'py-5 px-40' %>
      <div class="flex flex-row px-40">
        <%= f.radio_button :public_status , 'private', name: 'playlist[public_status]', class: "radio radio-accent", checked: @playlist_public==false %>
        <%= f.label :public_status, 'プライベート', value: 'private' %>
      </div>
      <div class="flex flex-row px-40 pt-3" >
        <%= f.radio_button :public_status , 'public', name: 'playlist[public_status]', class: "radio radio-accent", checked: @playlist_public==true %>
        <%= f.label :public_status, 'パブリック', value: 'public' %>
      </div>
    </div>
  </div>
  <div class="divider px-10 pt-10"></div>
  <div class="flex justify-center w-full px-10">
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>タイトル</th>
          <th>アーティスト</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody id="playlist-items" data-playlist-items="<%= @playlist_items.to_json %>">
        <% @playlist_items.each_with_index do |playlist_item, index| %>
          <tr class="table-row">
            <td><%= index+1 %></td>
            <td><%= playlist_item[0] %></td>
            <td><%= playlist_item[1] %></td>
            <td><button type="button" class="btn btn-outline btn-secondary" onclick="moveUp(<%= index %>)" > ↑ </button></td>
            <td><button type="button" class="btn btn-outline btn-secondary" onclick="moveDown(<%= index %>)"> ↓ </button></td>
            <td><button type="button" class="btn btn-outline btn-primary" onclick="removeItem(<%= index %>)"><%= " 削除 " %></button></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="divider px-10"></div>
  <div class="flex justify-center py-10 gap-10">
    <%= f.hidden_field :playlist_items, id: 'hidden_playlist_items', value: @playlist_items.to_json %>
    <%= f.hidden_field :current_playlist_items, value: @playlist_items.to_json %>
    <%= f.submit '保存', class: 'btn btn-primary', onclick:  'syncPlaylistItems()' %>
    <%= link_to 'キャンセル', playlist_path(@playlist), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/playlists/index.html.erb
<div class="flex w-full py-20 px-20">
    <h1 class="text-4xl font-bold font-body font-kosugi"><%= 'プレイリスト一覧' %></h1>
</div>

<!-- プレイリスト表示 -->
<div class="flex justify-center">
  <div class="grid grid-cols-2 gap-y-20 gap-x-0 w-full justify-items-center">
    <% @playlist_ids.each do |playlist_id| %>
      <%= render 'playlist_card', playlist_id: playlist_id %>
    <% end %>
  </div>
</div>

<div class="flex justify-center py-20">
  <%= paginate @user_playlist %>
</div>

app/views/playlists/select.html.erb
<div class="container">
  <div class="split left">
    <div class="h_select">
      <h1><%= 'お気に入りアーティストからプレイリストを作成する' %></h1>
    </div>
    <%= link_to "選ぶ", create_playlist_artists_path, class: "button_select button_blue" %>
  </div>
  <div class="split right">
    <div class="h_select">
      <h1><%= '音楽ジャンルからプレイリストを作成する' %></h1>
    </div>
    <%= link_to "選ぶ", create_playlist_genres_path, class: 'button_select button_pink' %>
  </div>
</div>

app/views/playlists/show.html.erb
<div class="w-full">
  <div class="px-20 pt-10">
    <%= link_to "← 一覧に戻る", playlists_path, class: "btn btn-outline btn-accent rounded-full" %>
  </div>
  <div class="flex justify-center py-10">
    <div class="border border-8 border-sky-400 w-4/5 rounded-3xl">
      <div class="card w-full bg-neutral pt-10">
        <div class="flex flex-col">
          <div class="flex flex-row">
            <div class="flex flex-col w-1/3 items-center p-4">
              <h1 class="text-4xl font-bold"><%= @playlist.name %></h1>
              <figure class="px-5 pt-10">
                <% playlist = RSpotify::Playlist.find(nil, @playlist.spotify_id) %>
                <% if playlist.images.any? %>
                  <% image = playlist.images.first %>
                  <img src="<%= image['url'] %>?size=300x300" alt="Playlist Artwork" class="rounded-xl" style="width: 250px; height: 250px;" />
                <% else %>
                  <img src="<%= image_path('20200501_noimage.png') %>" alt="Playlist Artwork" class="rounded-xl" style="width: 200px; height: 200px;" />
                <% end %>
              </figure>
              <div class="flex justify-center">
                <p class="text-base font-normal"><%= "作成日 : #{@playlist.date}" %></p>
              </div>
              <% spotify_url = "https://open.spotify.com/playlist/#{@playlist.spotify_id}" %>
              <% app_url = "https://discover-music.fly.dev" %>
              <div class="flex justify-center pt-10">
                <div class="flex flex-col gap-5">
                  <%= link_to spotify_url, class: "btn bg-gray-50 text-indigo-950 hover:bg-gray-200 hover:text-indigo-950" do %>
                  <%= image_tag "Spotify_Icon_RGB_Green.png", size: "20x20" %>
                    Spotifyで聴く
                  <% end %>
                  <%= link_to "編集する", edit_playlist_path(@playlist), class: "btn btn-accent" %>
                  <%= link_to  "https://twitter.com/share?url=#{CGI.escape(app_url)}&text=【Discover music】でプレイリストを作成しました#{CGI.escape(spotify_url)}", class: "btn bg-black text-slate-100 ", disabled: @playlist_public ? nil : "disabled" do  %>
                  <%= image_tag "logo-white.png", size: "12x12" %>
                    シェア
                  <% end %>
                </div>
              </div>
            </div>
            <div class="w-2/3 p-4">
              <table class="table">
                <thead>
                  <tr>
                    <th></th>
                    <th>タイトル</th>
                    <th>アーティスト</th>
                  </tr>
                </thead>
                <tbody>
                  <% @playlist_items.each_with_index do |playlist_item, index| %>
                    <tr class="table-row">
                      <td><%= index+1 %></td>
                      <td><%= playlist_item[0] %></td>
                      <td><%= playlist_item[1] %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
          <div class="px-5 py-5">
            <iframe style="border-radius: 12px;" src="https://open.spotify.com/embed/playlist/<%= @playlist.spotify_id %>" width="100%" height="152" frameborder="0" allowtransparency="true" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
          </div>
        </div>
      </div>
    <div>
  </div>
</div>