config/routes.rb
Rails.application.routes.draw do
  
  root 'top_pages#top'

  resources :users, only: %i[new create]
  
  get 'sign_up', to: 'users#new'
  get 'select_sign_up', to: 'users#select'
  get 'app_top', to: 'top_pages#app_top'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'guide_spotify_login', to: 'user_sessions#guide_spotify_login'

  post 'oauth/callback', to: 'google#callback'
  get 'oauth/callback', to: 'google#callback'
  get 'oauth/:provider', to: 'google#oauth', as: 'auth_at_provider'

  get 'user_sessions/google_auth', to: 'user_sessions#google_auth', as: 'google_login'
  get 'users/google_auth', to: 'users#google_auth', as: 'google_signup'
  
  get '/spotify_login', to: 'spotify#login'
  get '/spotify_callback', to: 'spotify#callback'

  get 'pre_sign_up', to: 'pre_sign_ups#new'
  post 'pre_sign_up', to: 'pre_sign_ups#create'
  get 'pre_sign_up_completed', to: 'pre_sign_ups#completed'

  resources :favorite_artists, only: %i[index create destroy] do
    collection do
      get :search
    end
  end

  get 'favorite_artists/new'

  resources :favorite_tracks, only: %i[index create destroy] do
    collection do
      get :search
    end
  end

  get 'favorite_tracks/new'

  get 'playlists/select'
  resources :playlists, only: %i[show index destroy edit update]

  resources :create_playlist_artists, only: %i[index create]

  resources :create_playlist_genres, only: %i[index create]

  resources :password_resets, only: %i[create edit update new]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/favorite_artist.rb
class FavoriteArtist < ApplicationRecord
  belongs_to :user
  belongs_to :artist
end

app/controllers/favorite_artists_controller.rb
class FavoriteArtistsController < ApplicationController
  before_action :set_favorite_artist, only: %i[destroy]

  def index
    @favorite_artists = FavoriteArtist.where(user: current_user).page(params[:page]).per(15)
    @artist_ids = @favorite_artists.map { |fa| fa.artist.spotify_id }
  end

  def new; end

  def create
    artist_params = favorite_artist_params
    artist_id = artist_params[:artist_id]
    artist_name = artist_params[:artist_name]

    # アーティストが選択されていなかった場合、処理を終了
    if artist_id.blank?
      return
    end

    if Artist.exists?(spotify_id: artist_id)
      @artist = Artist.find_by(spotify_id: artist_id)
    else
      @artist = Artist.new(name: artist_name, spotify_id: artist_id)
      unless @artist.save
        flash.now[:error] = "アーティストの登録に失敗しました"
        render 'new'
        return
      end
    end

    if FavoriteArtist.exists?(user: current_user, artist: @artist)
      flash[:alert] = 'すでにお気に入りに登録済みです'
      redirect_to favorite_artists_path
    else
      @favorite_artist = FavoriteArtist.new(user: current_user, artist: @artist)
      if @favorite_artist.save
        flash[:success] = 'お気に入りに追加しました'
        redirect_to favorite_artists_path
      else
        flash[:error] = 'お気に入りの登録に失敗しました'
        render 'new'
      end
    end
  end

  def search
    artist_name = params[:artist_name]

    if artist_name.present?
      query = "artist:\"#{params[:artist_name]}*\""
    end

    if query.present?
      @artists = RSpotify::Artist.search(query, market:'JP', limit:20)
      if @artists.present?
        @top_tracks = {}
        @artists.each do |artist|
          artist_id = artist.id
          @top_tracks[artist_id] = RSpotify::Artist.find(artist_id).top_tracks('JP').first
        end
      else
        flash.now[:alert] = '該当するアーティストが見つかりませんでした'
      end
    else
      flash.now[:warning] = 'アーティスト名を入力してください'
    end
    render 'new'
  end

  def destroy
    @favorite_artist.destroy!
    flash[:success] = "お気に入りから削除しました"
    redirect_to favorite_artists_path, status: :see_other
  end

  private

  def favorite_artist_params
    params.require(:favorite_artist).permit(:artist_name, :artist_id)
  end

  def set_favorite_artist
    @favorite_artist = FavoriteArtist.find(params[:id])
  end    
end

app/helpers/favorite_artists_helper.rb
module FavoriteArtistsHelper
end

app/views/favorite_artists/_artist_card.html.erb
<div class="card w-96 bg-secondary shadow-xl">
  <div class="card-actions justify-end px-2 pt-2">
    <%= render "delete_button", artist_id: artist_id %>
  </div>  
  <figure class="px-10 pt-3">
    <% artists = RSpotify::Artist.find(artist_id) %>
    <% if artists.images.present? %>
      <% image = artists.images.first %>
      <img src="<%= image['url'] %>?size=320x320" alt="Artists Artwork" class="rounded-xl" style="width: 300px; height: 300px;" />
    <% else %>
      <img src="<%= image_path('20200501_noimage.png') %>" alt="Artists Artwork" class="rounded-xl" style="width: 300px; height: 300px;" />
    <% end %>
  </figure>
  <div class="card-body items-center text-center">
    <h2 class="card-title text-indigo-950">
      <%= Artist.find_by(spotify_id: artist_id).name %>
    </h2>
  </div>
</div>

app/views/favorite_artists/_artist_table.html.erb
<div class="flex justify-center">
  <div class="overflow-y-scroll border border-gray-200 p-4 w-4/5 h-[40vh] pt-0">
    <table class="table table-pin-rows">
      <thead>
        <tr>
          <th></th>
          <th>アーティスト名</th>
          <th>トップトラック</th>
        </tr>
      </thead>
      <tbody>
        <% if @artists.present? %>
          <% @artists.each do |artist| %>
            <tr class="table-row cursor-pointer hover:bg-base-300">
              <td class="radio border-none">
                <%= f.radio_button :artist_id, artist.id, name: 'favorite_artist[artist_id]', class: "radio radio-accent", data: { artist_name: artist.name } %>
              </td>
              <td class="artist-name"><%= "#{artist.name}" %></td>
              <td class="artist_toptrack">
                <% if @top_tracks.present? && @top_tracks[artist.id].present? %>
                  <%= "#{@top_tracks[artist.id].name}" %>
                <% else %>
                  <%= "トップトラックが見つかりませんでした" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/favorite_artists/_delete_button.html.erb
<button class="btn btn-square btn-sm" onclick="document.getElementById('delete_confirmation_<%= artist_id %>').showModal()">
  <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" /></svg>
</button>

<!-- ダイアログ表示 -->
<dialog id="delete_confirmation_<%= artist_id %>" class="modal">
  <div class="modal-box">
    <p class="text-center">
      <%= "#{Artist.find_by(spotify_id: artist_id).name}をお気に入りから削除しますか?" %>
    </p>
    <div class="modal-action">
      <form method="dialog">
        <button class="btn">キャンセル</button>
      </form>
      <% favorite_artist = FavoriteArtist.find_by(artist: Artist.find_by(spotify_id: artist_id), user: current_user) %>
      <%= button_to "削除する", favorite_artist_path(favorite_artist), method: :delete, class: "btn btn-warning" %>
    </div>
  </div>
</dialog>

app/views/favorite_artists/_search_form.html.erb
<div class="flex justify-center py-6">
  <div class="join w-full">
    <%= form_with url: search_favorite_artists_path, method: :get, class: "w-full flex justify-center" do |f| %>
      <%= f.text_field :artist_name, class: "input input-bordered input-secondary w-1/4 join-item", placeholder: "アーティスト名" %>
      <%= f.submit "検索", class: "btn join-item bg-accent text-indigo-950 hover:bg-secondary rounded-r-full" %>
    <% end %>
  </div>
</div>

app/views/favorite_artists/index.html.erb
<div class="flex justify-between w-full py-20 px-20">
    <h1 class="text-4xl font-bold font-body font-kosugi"><%= 'アーティスト一覧' %></h1>
    <%= link_to "お気に入り登録", favorite_artists_new_path, class: "btn btn-lg btn-outline btn-accent rounded-full" %>
</div>

<!-- アーティスト表示 -->
<div class="flex justify-center">
  <div class="grid grid-cols-3 gap-10">
    <% @artist_ids.each do |artist_id| %>
      <%= render "artist_card", artist_id: artist_id %>
    <% end %>
  </div>
</div>

<div class="flex justify-center py-20">
  <%= paginate @favorite_artists %>
</div>

app/views/favorite_artists/new.html.erb
<div class="flex justify-between px-20 py-10">
  <h1 class="text-3xl font-bold font-body font-kosugi"><%= "お気に入りアーティスト登録" %></h1>
  <div class="pr-10">
    <%= link_to "← 一覧に戻る", favorite_artists_path, class: "btn btn-outline btn-accent rounded-full" %>
  </div>
</div>

<%= render "search_form" %>

<%= form_with url: favorite_artists_path, method: :post do |f| %>
  <%= render "artist_table", f: f %>
  <%= f.hidden_field :artist_name, value: "" , name: "favorite_artist[artist_name]" %> 
  <div class="flex justify-end pt-10 px-40">
    <%= f.submit "登録",  class: "btn btn-lg btn-active btn-accent text-indigo-950 hover:bg-base-100 hover:text-accent rounded-full px-10" %>
  </div>
<% end %>